// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkULh9QOBNazgx_qJXw0esTJC2rzVYyA',
    appId: '1:635820804420:web:6aae81f47cfa189eb22f11',
    messagingSenderId: '635820804420',
    projectId: 'mess-tokens',
    authDomain: 'mess-tokens.firebaseapp.com',
    storageBucket: 'mess-tokens.firebasestorage.app',
    measurementId: 'G-WS46ZZ03T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWl3mo_IPRZ4dk3lbABZovK4yju-4978',
    appId: '1:635820804420:android:503cce87212fcb0eb22f11',
    messagingSenderId: '635820804420',
    projectId: 'mess-tokens',
    storageBucket: 'mess-tokens.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkp_AwJZEF0pqE9ULIdXNZ8qXJ3blmaKU',
    appId: '1:635820804420:ios:faf6fa5894441cc6b22f11',
    messagingSenderId: '635820804420',
    projectId: 'mess-tokens',
    storageBucket: 'mess-tokens.firebasestorage.app',
    iosBundleId: 'com.example.tokenSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkp_AwJZEF0pqE9ULIdXNZ8qXJ3blmaKU',
    appId: '1:635820804420:ios:faf6fa5894441cc6b22f11',
    messagingSenderId: '635820804420',
    projectId: 'mess-tokens',
    storageBucket: 'mess-tokens.firebasestorage.app',
    iosBundleId: 'com.example.tokenSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXkULh9QOBNazgx_qJXw0esTJC2rzVYyA',
    appId: '1:635820804420:web:e26a84813dead740b22f11',
    messagingSenderId: '635820804420',
    projectId: 'mess-tokens',
    authDomain: 'mess-tokens.firebaseapp.com',
    storageBucket: 'mess-tokens.firebasestorage.app',
    measurementId: 'G-KK429693T6',
  );
}
